
name: autopackage_and_policy_scan

on:
  workflow_dispatch:

jobs:
  checkout-and-package:
    runs-on: macos-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: install gen-ir
        env:
          HOMEBREW_NO_REQUIRE_TAP_TRUST: "1"  # Bypasses the strict tap verification failures
        run: |
          brew tap veracode/tap
          brew install veracode/tap/gen-ir

      - name: package artifact
        run: |
          xcodebuild clean archive \
            -project 'Food Truck.xcodeproj' \
            -scheme 'Food Truck' \
            -destination 'generic/platform=iOS' \
            -configuration Debug \
            -archivePath 'Food Truck.xcarchive' \
            DEBUG_INFORMATION_FORMAT=dwarf-with-dsym \
            ENABLE_BITCODE=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO

      - name: save artifact
        uses: actions/upload-artifact@v4
        with:
            name: veracode-artifact
            path: veracode-artifacts
